# 잠수상태로 진입하는 시간
AfkStart: 60

# 포인트를 지급하는 간격
AfkPeriod: 60

# 잠수포인트 메시지 포맷설정
UserMessage: '&6놀이터 &fㅣ 현재 잠수포인트는 &9[POINT] &f입니다.'

# 잠수 어드민 명령어 메시지 설정
AdminMessage:
  - ' '
  - '&6놀이터 &fㅣ &c/잠수관리 지급 [플레이어] [포인트] - &6플레이어에게 잠수포인트를 지급합니다.'
  - '&6놀이터 &fㅣ &c/잠수관리 회수 [플레이어] [포인트] - &6플레이어에게서 잠수포인트를 회수합니다.'
  - '&6놀이터 &fㅣ &c/잠수관리 설정 [플레이어] [포인트] - &6플레이어의 잠수포인트를 설정합니다.'
  - '&6놀이터 &fㅣ &c/잠수관리 확인 [플레이어] - &6플레이어의 잠수포인트를 확인합니다.'

# 커맨드를 잘못 입력하였을때
CommandError: '&6놀이터 &fㅣ &c명령어를 잘못 입력했습니다. &f/잠수관리'

# /잠수관리 명령어가 성공했을때 유저와 관리자에게 전달하는 메시지
AddMessage:
  ForUser: '&6놀이터 &fㅣ 관리자가 당신에게 &9[POINT] &f잠수포인트를 지급하였습니다.'
  ForAdmin: '&6놀이터 &fㅣ 유저 &9[PLAYER] &f에게 잠수포인트 &9[POINT] &f를 지급하였습니다.'

RemoveMessage:
  ForUser: '&6놀이터 &fㅣ 관리자가 당신의 잠수포인트를 &9[POINT] &f만큼 차감하였습니다.'
  ForAdmin: '&6놀이터 &fㅣ 유저 &9[PLAYER] &f의 잠수포인트를 &9[POINT] &f만큼 차감하였습니다.'

SetMessage:
  ForUser: '&6놀이터 &fㅣ 관리자가 당신의 잠수포인트를 &9[POINT] &f으로 설정하였습니다.'
  ForAdmin: '&6놀이터 &fㅣ 유저 &9[PLAYER] &f의 잠수포인트를 &9[POINT] &f으로 설정하였습니다.'

SearchMessage:
  ForAdmin: '&6놀이터 &fㅣ 유저 &9[PLAYER] &f의 잠수포인트 : &9[POINT]'

# 타이틀 포맷 설정
TitleFormat:
  Enabled:
    Title: '&6놀이터 &fㅣ &9잠수 중입니다...'
    SubTitle: '&f[HOUR] : [MINUTE] : [SECOND] &6포인트 : [POINT]&7(+[RECEIVED])'
  Disabled:
    Title: '&6놀이터 &fㅣ &c잠수가 종료되었습니다.'
    SubTitle: '&f[HOUR] : [MINUTE] : [SECOND] &6포인트 : [POINT]&7(+[RECEIVED])'