# 잠수상태로 진입하는 시간
AfkStart: 60

# 포인트를 지급하는 간격
AfkPeriod: 60

# 잠수포인트 메시지 포맷설정
UserMessage: '&c[&aG&d] &fㅣ 현재 잠수포인트는 &9%afk_point% &f입니다.'

# 잠수 어드민 명령어 메시지 설정
AdminMessage:
  - ' '
  - '&c[&aG&d] &fㅣ &c/잠수관리 지급 [플레이어] [포인트] - &6플레이어에게 잠수포인트를 지급합니다.'
  - '&c[&aG&d] &fㅣ &c/잠수관리 회수 [플레이어] [포인트] - &6플레이어에게서 잠수포인트를 회수합니다.'
  - '&c[&aG&d] &fㅣ &c/잠수관리 설정 [플레이어] [포인트] - &6플레이어의 잠수포인트를 설정합니다.'
  - '&c[&aG&d] &fㅣ &c/잠수관리 확인 [플레이어] - &6플레이어의 잠수포인트를 확인합니다.'

# 커맨드를 잘못 입력하였을때
CommandError: '&c[&aG&d] &fㅣ &c명령어를 잘못 입력했습니다. &f/잠수관리'

# /잠수관리 명령어가 성공했을때 유저와 관리자에게 전달하는 메시지
AddMessage:
  ForUser: '&c[&aG&d] &fㅣ 관리자가 당신에게 &9%afk_point% &f잠수포인트를 지급하였습니다.'
  ForAdmin: '&c[&aG&d] &fㅣ 유저 &9%afk_player% &f에게 잠수포인트 &9%afk_point% &f를 지급하였습니다.'

RemoveMessage:
  ForUser: '&c[&aG&d] &fㅣ 관리자가 당신의 잠수포인트를 &9%afk_point% &f만큼 차감하였습니다.'
  ForAdmin: '&c[&aG&d] &fㅣ 유저 &9%afk_player% &f의 잠수포인트를 &9%afk_point% &f만큼 차감하였습니다.'

SetMessage:
  ForUser: '&c[&aG&d] &fㅣ 관리자가 당신의 잠수포인트를 &9%afk_point% &f으로 설정하였습니다.'
  ForAdmin: '&c[&aG&d] &fㅣ 유저 &9%afk_player% &f의 잠수포인트를 &9%afk_point% &f으로 설정하였습니다.'

SearchMessage:
  ForAdmin: '&c[&aG&d] &fㅣ 유저 &9%afk_player% &f의 잠수포인트 : &9%afk_point%'

# 타이틀 포맷 설정
TitleFormat:
  Enabled:
    Title: '&c[&aG&d] &fㅣ &9잠수 중입니다...'
    SubTitle: '&f%afk_hour% : %afk_minute% : %afk_second% &6포인트 : %afk_point%&7(+%received_point%)'
  Disabled:
    Title: '&c[&aG&d] &fㅣ &c잠수가 종료되었습니다.'
    SubTitle: '&f%afk_hour% : %afk_minute% : %afk_second% &6포인트 : %afk_point%&7(+%received_point%)'

ReloadMessage: '&c[&aG&d] &fㅣ &6콘피그를 리로드하였습니다.'
SaveMessage: '&c[&aG&d] &fㅣ &6유저 데이터를 저장하였습니다.'